#!/usr/bin/env ruby
# encoding: utf-8

require File.expand_path("../../config/environment",  __FILE__)

users = [
  "Trinity St. Clair",
  "Sara Luvv",
  "Rikki Six",
  "Brett Rossi",
  "BiBi Jones",
  "Veronica Rodriguez",
  "Layla Rose",
  "Malena Morgan",
  "Dillion Harper",
  "Madison Scott",
  "August Ames",
  "Molly Cavalli",
  "Ella Milano",
  "Stoya",
  "Jesse Jane",
  "Kayden Kross",
  "Riley Steele",
  "Lexi Belle",
  "Riley Reid",
  "Ron Jeremy",
  "James Deen",
  "Evan Stone",
  "Manuel Ferrara",
  "Mick Blue",
  "Tommy Gunn",
  "Ben English",
  "Peter North",
  "Lexington Steele"
]

$redis.multi
$redis.del("users")
users.each do |user|
  $redis.lpush("users", user)
end
$redis.exec